name: Build and Publish

on:
  push:
    branches: [main]
  workflow_dispatch:

    
jobs:
  docker:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build Base Image locally
        uses: docker/build-push-action@v5
        with:
          context: ./base
          push: true
          tags: localhost:5000/j4n11s/browser-v6:base



      - name: Build Brave
        uses: docker/build-push-action@v5
        with:
          context: ./browser/brave
          push: true
          tags: j4n11s/browser-v6-img:brave
        
      - name: Build Chrome
        uses: docker/build-push-action@v5
        with:
          context: ./browser/chrome
          push: true
          tags: j4n11s/browser-v6-img:chrome


      - name: Build Firefox
        uses: docker/build-push-action@v5
        with:
          context: ./browser/firefox
          push: true
          tags: j4n11s/browser-v6-img:firefox

      - name: Build Tor
        uses: docker/build-push-action@v5
        with:
          context: ./browser/tor
          push: true
          tags: j4n11s/browser-v6-img:tor
