name: Build and Publish

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build Base Image
        uses: docker/build-push-action@v2
        with:
          context: ./base
          tags: base
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build Chrome Image
        uses: docker/build-push-action@v2
        with:
          context: ./browser/chrome
          tags: j4n11s/browser-v6:chrome
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}