name: Build and Publish

on:
  push:
    branches: [main]
  workflow_dispatch:

    
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build Base
        uses: docker/build-push-action@v5
        with:
          context: ./base
          push: false
          tags: base
      -
        name: Build Chrome
        uses: docker/build-push-action@v5
        with:
          context: ./browser/chrome
          push: true
          tags: j4n11s/browser-v6:chrome